"""Add title column to journal_entries table

Revision ID: dc79b119d50f
Revises: 5dbe85c8b94c
Create Date: 2025-05-29 11:41:26.651496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc79b119d50f'
down_revision: Union[str, None] = '5dbe85c8b94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'title')
    # ### end Alembic commands ###
